const mongoose = require("mongoose");
const Category = require("./Category");

const courseSchema = new mongoose.Schema({
    courseName:{
        type:String,
        required:true,
        trim:true
    },
    courseDescription:{
        type:String,
        required:true,
        trim:true
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    whatYouWillLearn:{
        type:String,
        required:true,
        trim:true,
    },
    courseContent:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Section",
            required:true
        }
    ],
    ratingAndReviews:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"RatingAndReviews"
        }
    ],
    price:{
        type:Number,
        required:true,
    },
    thumbnail:{
        type:String,
        required:true,
    },
    category:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Category"
        }
    ],
    studentEnrolled:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    tag:{
        type:String,
        required:true
    },
    instructions:{
        type:String,
    },
    status:{
        type:String,
        enum: ["Draft","Published"]
    },
    createdAt:{
        type:Date,
        default:Date.now()
    },
    totalDurationCourse:{
        type:String
    },
    progressPercentage:{
        type:String
    }
});

module.exports = mongoose.model("Course",courseSchema);